# Generated by Django 4.1.7 on 2023-04-01 13:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, max_length=90, primary_key=True, serialize=False, unique=True)),
                ('task_name', models.CharField(max_length=200)),
                ('complete', models.BooleanField()),
            ],
        ),
    ]
